### ISSUE TITLE
Error while running the tool

### ISSUE THREAD

**Issue by adharshkamath** [wu-haoze/Lemur-program-verification#1]
I tried running the `run_exp_gpt4.sh` script in the `code2inv/` directory with the following arguments:
```
./run_exp_gpt4.sh ./benchmarks/code2inv/c/1
```
and I got the following exception:
```
Traceback (most recent call last):
  File "/mnt/c/Users/user/repos/Lemur-program-verification/code2inv/./src/run.py", line 41, in <module>
    v = Verifier(task, VERIFIERS, args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/user/repos/Lemur-program-verification/code2inv/src/verifier.py", line 38, in __init__
    self.program = Program(r.lines_to_verify, r.replacement)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/user/repos/Lemur-program-verification/code2inv/src/program.py", line 61, in __init__
    if line.strip().split()[0] in ["for", "do", "while"]:
       ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Before running the `run_exp_gpt4.sh` script, I installed the packages in `requirements.txt` and ran the `./build.sh` script.
Is there any additional setup I need to complete for the tool before running it? Or pass any other CLI arguments?

**Comment by wu-haoze** [comment]
Hi @adharshkamath , I think those should be sufficient dependencies. I can't seem to reproduce the issue on my end. I'm running python 3.10. Have you installed clang-format on your machine?

**Comment by adharshkamath** [comment]
Thanks for the response! Yes, I have `clang-format-15` installed on my machine from running the `build.sh` script.

**Comment by wu-haoze** [comment]
@adharshkamath perhaps try the package versions [here](https://github.com/wu-haoze/Lemur-program-verification/blob/main/requirements.txt)?

**Comment by adharshkamath** [comment]
Hi @wu-haoze , thank you for your reply. I tried installing the packages with the same versions from the requirements.txt file but I'm still getting the same error. Please let me know if there's any other setup step I'm missing.

**Comment by adharshkamath** [comment]
Here are the steps I took to run Lemur in a fresh setup:
I setup a new conda environment with python 3.8:
```
conda create -n lemur python=3.8
```
Then I installed the packages:
```
pip install -r requirements.txt
```
Then I ran the `build.sh` script. clang-format-15 is installed, and I verified it by running:
```
❯ clang-format-15 --version
Ubuntu clang-format version 15.0.7
```
I can also see UAutomizer and ESBMC downloaded into the `tools/` directory.
When I run:
```
./run_exp_gpt3.sh benchmarks/sv_comp/c/array-crafted_zero_sum_const1_assertion0
```
I get the following output:
```
benchmarks/sv_comp/c/array-crafted_zero_sum_const1_assertion0
array-crafted_zero_sum_const1_assertion0
Namespace(input='benchmarks/sv_comp/c/array-crafted_zero_sum_const1_assertion0.yml', learn=True, model='gpt-3.5-turbo', no_repair=False, num_assertions=2, num_attempts=4, per_instance_timeout=30, prop='reach', seed=1, simulate=False, verbosity=1, verifier='all', working_dir='data_sv_comp_gpt3_')
{'format_version': '2.0', 'input_files': 'array-crafted_zero_sum_const1_assertion0.c', 'options': {'data_model': 'ILP32', 'language': 'C'}, 'properties': [{'expected_verdict': True, 'property_file': '../properties/unreach-call.prp'}, {'property_file': '../properties/coverage-branches.prp'}, {'property_file': '../properties/coverage-conditions.prp'}, {'property_file': '../properties/coverage-statements.prp'}]}
Working directory created: /home/adharsh/repos/Lemur-program-verification/lemur/data_sv_comp_gpt3_/array-crafted_zero_sum_const1_assertion0
Traceback (most recent call last):
  File "./src/run.py", line 39, in <module>
    v = Verifier(task, VERIFIERS, args)
  File "/home/adharsh/repos/Lemur-program-verification/lemur/src/verifier.py", line 39, in __init__
    self.program = Program(r.lines_to_verify, r.replacement)
  File "/home/adharsh/repos/Lemur-program-verification/lemur/src/program.py", line 62, in __init__
    if line.strip().split()[0] in ["for", "do", "while"]:
IndexError: list index out of range
```
Please let me know if I'm missing any step. Thank you!

**Comment by adharshkamath** [comment]
@wu-haoze  I think I understood the error. The path to clang_format was hardcoded in `gloal_configuations.py`.
I've submitted a PR that could fix this issue. Please see #5
